---
# tasks file for mi_primer_role

- name: Incluir tarea saludar
  include: saludar.yml
  when:
    - role_action == "saludar"

- name: Force un fail
  fail:
    msg: "esto ha fallado"
  when:
    - role_action == "fail"
- name: Incluir tarea despedir
  include: despedir.yml
  when:
    - role_action == "despedir"

